# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"\"\n\nSumRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x15\n\x08SumReply\x12\t\n\x01s\x18\x01 \x01(\x01\"\'\n\x0fMultiplyRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x1a\n\rMultiplyReply\x12\t\n\x01s\x18\x01 \x01(\x01\".\n\x0bMax3Request\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\x12\t\n\x01\x63\x18\x03 \x01(\x01\"\x16\n\tMax3Reply\x12\t\n\x01s\x18\x01 \x01(\x01\"%\n\rDivModRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\'\n\x0b\x44ivModReply\x12\x0b\n\x03\x64iv\x18\x01 \x01(\x05\x12\x0b\n\x03mod\x18\x02 \x01(\x05\x32\x9d\x01\n\nCalculator\x12\x1d\n\x03Sum\x12\x0b.SumRequest\x1a\t.SumReply\x12\'\n\x08Multiply\x12\x10.MultiplyRequest\x1a\t.SumReply\x12\x1f\n\x04Max3\x12\x0c.Max3Request\x1a\t.SumReply\x12&\n\x06\x44ivMod\x12\x0e.DivModRequest\x1a\x0c.DivModReplyb\x06proto3')



_SUMREQUEST = DESCRIPTOR.message_types_by_name['SumRequest']
_SUMREPLY = DESCRIPTOR.message_types_by_name['SumReply']
_MULTIPLYREQUEST = DESCRIPTOR.message_types_by_name['MultiplyRequest']
_MULTIPLYREPLY = DESCRIPTOR.message_types_by_name['MultiplyReply']
_MAX3REQUEST = DESCRIPTOR.message_types_by_name['Max3Request']
_MAX3REPLY = DESCRIPTOR.message_types_by_name['Max3Reply']
_DIVMODREQUEST = DESCRIPTOR.message_types_by_name['DivModRequest']
_DIVMODREPLY = DESCRIPTOR.message_types_by_name['DivModReply']
SumRequest = _reflection.GeneratedProtocolMessageType('SumRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:SumRequest)
  })
_sym_db.RegisterMessage(SumRequest)

SumReply = _reflection.GeneratedProtocolMessageType('SumReply', (_message.Message,), {
  'DESCRIPTOR' : _SUMREPLY,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:SumReply)
  })
_sym_db.RegisterMessage(SumReply)

MultiplyRequest = _reflection.GeneratedProtocolMessageType('MultiplyRequest', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPLYREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:MultiplyRequest)
  })
_sym_db.RegisterMessage(MultiplyRequest)

MultiplyReply = _reflection.GeneratedProtocolMessageType('MultiplyReply', (_message.Message,), {
  'DESCRIPTOR' : _MULTIPLYREPLY,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:MultiplyReply)
  })
_sym_db.RegisterMessage(MultiplyReply)

Max3Request = _reflection.GeneratedProtocolMessageType('Max3Request', (_message.Message,), {
  'DESCRIPTOR' : _MAX3REQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Max3Request)
  })
_sym_db.RegisterMessage(Max3Request)

Max3Reply = _reflection.GeneratedProtocolMessageType('Max3Reply', (_message.Message,), {
  'DESCRIPTOR' : _MAX3REPLY,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Max3Reply)
  })
_sym_db.RegisterMessage(Max3Reply)

DivModRequest = _reflection.GeneratedProtocolMessageType('DivModRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIVMODREQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:DivModRequest)
  })
_sym_db.RegisterMessage(DivModRequest)

DivModReply = _reflection.GeneratedProtocolMessageType('DivModReply', (_message.Message,), {
  'DESCRIPTOR' : _DIVMODREPLY,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:DivModReply)
  })
_sym_db.RegisterMessage(DivModReply)

_CALCULATOR = DESCRIPTOR.services_by_name['Calculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMREQUEST._serialized_start=20
  _SUMREQUEST._serialized_end=54
  _SUMREPLY._serialized_start=56
  _SUMREPLY._serialized_end=77
  _MULTIPLYREQUEST._serialized_start=79
  _MULTIPLYREQUEST._serialized_end=118
  _MULTIPLYREPLY._serialized_start=120
  _MULTIPLYREPLY._serialized_end=146
  _MAX3REQUEST._serialized_start=148
  _MAX3REQUEST._serialized_end=194
  _MAX3REPLY._serialized_start=196
  _MAX3REPLY._serialized_end=218
  _DIVMODREQUEST._serialized_start=220
  _DIVMODREQUEST._serialized_end=257
  _DIVMODREPLY._serialized_start=259
  _DIVMODREPLY._serialized_end=298
  _CALCULATOR._serialized_start=301
  _CALCULATOR._serialized_end=458
# @@protoc_insertion_point(module_scope)
